### ISSUE TITLE
detect uBlock Popup blocker

### ISSUE THREAD

**Issue by redimongo** [aruniverse/adblock-detect-react#25]
We have just had one of our clients, say to us that they use uBlock and they tried to do a payment on our website, which requires a popup to launch and them to verify the card owner details with their bank (normally done via SMS or an Auth app)

However uBlock blocked the popup, which has now caused the customer grief.

**Describe the solution you'd like**
We would like to be able to disable the submit button or/and display a banner saying please disable uBlock  for this website.
this one (https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm)

**Comment by aruniverse** [comment]
should be resolved with v1.2.0, #26
