### ISSUE TITLE
Keep only JS files, not JSX

### ISSUE THREAD

**Issue by zhe1ka** [aruniverse/adblock-detect-react#30]
Hello. I use a custom webpack configuration which doesn't support JSX (only JS/TS/TSX) and when I run a project I have this issue. It's clear what's wrong and a possible solution is to add a specific loader for JSX. But, is it possible to keep only js files inside this package?
<img width="1150" alt="image" src="https://github.com/aruniverse/adblock-detect-react/assets/6460571/d90c15e0-66f8-4080-b319-95d7baf0676b">

**Comment by mmarifat** [comment]
Same for me now

![image](https://github.com/aruniverse/adblock-detect-react/assets/26267698/6b32d0b7-17cc-42a2-9e15-2eeeb637e7c6)

**Comment by aruniverse** [comment]
fixed in #31
