### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by vinodmmm** [aruniverse/adblock-detect-react#8]
I have AdBlock Plus installed on my browser and on my website it is not working anymore. It need's to be updated.

**Comment by aruniverse** [comment]
Please provide more details such as:

 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Comment by asotoglez** [comment]
same problem here
Browser Chrome Version  88.0.4324.104

**Comment by aruniverse** [comment]
Should be fixed in v1.0.3

**Comment by hassanazimi** [comment]
not working

**Comment by aruniverse** [comment]
> not working

Could you provide more info?
What's the package version you're using?
What browser and version are you using where it's not working?

Have you verified that you're able to reproduce this with the live demo site? Link to that in the readme at the root of the repo

**Comment by hassanazimi** [comment]
Adblocker: uBlock Origin
Chrome Version 88.0.4324.192 (Official Build) (x86_64)
"react": "^16.8.6",
PS your live demo site screenshot:

<img width="1178" alt="Screenshot 2021-02-24 at 12 53 11" src="https://user-images.githubusercontent.com/4809004/109003388-4be35780-769f-11eb-8a4a-0ecfc94f5fc4.png">

**Comment by aruniverse** [comment]
> Adblocker: uBlock Origin
> Chrome Version 88.0.4324.192 (Official Build) (x86_64)
> "react": "^16.8.6",
> PS your live demo site screenshot:
> 
> <img alt="Screenshot 2021-02-24 at 12 53 11" width="1178" src="https://user-images.githubusercontent.com/4809004/109003388-4be35780-769f-11eb-8a4a-0ecfc94f5fc4.png">
> 
> Im using
> 
> ```js
> <AdBlockDetectedWrapper>
>     <div>{'Hello Ad Blocked Page'}</div>
> </AdBlockDetectedWrapper>
> ```

Sorry it took so long, but v1.0.4 has been published to npm and should work
